-- V3 初始结构：认证 + 设备 + 可同步业务表（软删 + 版本）+ 变更日志 + 冲突日志。
-- 所有业务表以 (user_id, sync_id) 唯一定位；引用列存对方 sync_id，不建跨业务外键。

CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR(255) NOT NULL UNIQUE,
    password_hash   VARCHAR(255) NOT NULL,
    email_verified  BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP WITH TIME ZONE  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP WITH TIME ZONE  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMP WITH TIME ZONE
);

CREATE TABLE email_verification_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash  VARCHAR(64)  NOT NULL UNIQUE,
    expires_at  TIMESTAMP WITH TIME ZONE  NOT NULL,
    used_at     TIMESTAMP WITH TIME ZONE,
    created_at  TIMESTAMP WITH TIME ZONE  NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_evt_user ON email_verification_tokens (user_id);

CREATE TABLE devices (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    device_id    VARCHAR(64)  NOT NULL,
    device_name  VARCHAR(128) NOT NULL DEFAULT '',
    platform     VARCHAR(32)  NOT NULL DEFAULT '',
    app_version  VARCHAR(32)  NOT NULL DEFAULT '',
    last_seen_at TIMESTAMP WITH TIME ZONE  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at   TIMESTAMP WITH TIME ZONE  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revoked_at   TIMESTAMP WITH TIME ZONE,
    UNIQUE (user_id, device_id)
);

CREATE TABLE refresh_tokens (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    device_row_id  BIGINT      NOT NULL REFERENCES devices (id) ON DELETE CASCADE,
    token_hash     VARCHAR(64) NOT NULL UNIQUE,
    expires_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at     TIMESTAMP WITH TIME ZONE,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_refresh_user_device ON refresh_tokens (user_id, device_row_id);

CREATE TABLE categories (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    sync_id             VARCHAR(36) NOT NULL,
    name                VARCHAR(64) NOT NULL,
    icon                VARCHAR(32) NOT NULL DEFAULT '',
    type                INT         NOT NULL,
    sort_order          INT         NOT NULL DEFAULT 0,
    is_default          BOOLEAN     NOT NULL DEFAULT FALSE,
    version             BIGINT      NOT NULL DEFAULT 0,
    server_received_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          BIGINT      NOT NULL DEFAULT 0,
    is_deleted          BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, sync_id)
);

CREATE TABLE accounts (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    sync_id             VARCHAR(36) NOT NULL,
    name                VARCHAR(64) NOT NULL,
    type                INT         NOT NULL,
    initial_balance     BIGINT      NOT NULL DEFAULT 0,
    balance             BIGINT      NOT NULL DEFAULT 0,
    is_credit           BOOLEAN     NOT NULL DEFAULT FALSE,
    sort_order          INT         NOT NULL DEFAULT 0,
    is_archived         BOOLEAN     NOT NULL DEFAULT FALSE,
    version             BIGINT      NOT NULL DEFAULT 0,
    server_received_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          BIGINT      NOT NULL DEFAULT 0,
    is_deleted          BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, sync_id)
);

CREATE TABLE transactions (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                  BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    sync_id                  VARCHAR(36)  NOT NULL,
    type                     INT          NOT NULL,
    amount                   BIGINT       NOT NULL,
    date                     BIGINT       NOT NULL,
    time                     VARCHAR(8)   NOT NULL DEFAULT '00:00',
    note                     TEXT,
    category_sync_id         VARCHAR(36),
    account_sync_id          VARCHAR(36),
    transfer_account_sync_id VARCHAR(36),
    version                  BIGINT       NOT NULL DEFAULT 0,
    server_received_at       TIMESTAMP WITH TIME ZONE  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               BIGINT       NOT NULL DEFAULT 0,
    is_deleted               BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at               TIMESTAMP WITH TIME ZONE  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, sync_id)
);
CREATE INDEX idx_tx_user_date ON transactions (user_id, date);
CREATE INDEX idx_tx_category_ref ON transactions (user_id, category_sync_id);
CREATE INDEX idx_tx_account_ref ON transactions (user_id, account_sync_id);

-- 总预算哨兵：category_sync_id = ''（空串）。不能用 NULL——PG 唯一索引视 NULL 互不相等。
CREATE TABLE budgets (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    sync_id             VARCHAR(36) NOT NULL,
    budget_year         INT         NOT NULL,
    budget_month        INT         NOT NULL,
    category_sync_id    VARCHAR(36) NOT NULL DEFAULT '',
    amount              BIGINT      NOT NULL,
    version             BIGINT      NOT NULL DEFAULT 0,
    server_received_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          BIGINT      NOT NULL DEFAULT 0,
    is_deleted          BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, sync_id),
    UNIQUE (user_id, budget_year, budget_month, category_sync_id)
);

CREATE TABLE recurring_transactions (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    sync_id            VARCHAR(36)  NOT NULL,
    name               VARCHAR(64)  NOT NULL,
    type               INT          NOT NULL,
    amount             BIGINT       NOT NULL,
    category_sync_id   VARCHAR(36),
    account_sync_id    VARCHAR(36),
    frequency          INT          NOT NULL,
    repeat_interval    INT          NOT NULL DEFAULT 1,
    start_date         BIGINT       NOT NULL,
    end_date           BIGINT       NOT NULL DEFAULT 0,
    next_run_date      BIGINT       NOT NULL,
    anchor_day_of_month INT         NOT NULL DEFAULT 0,
    is_enabled         BOOLEAN      NOT NULL DEFAULT TRUE,
    note               TEXT,
    version            BIGINT       NOT NULL DEFAULT 0,
    server_received_at TIMESTAMP WITH TIME ZONE  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         BIGINT       NOT NULL DEFAULT 0,
    is_deleted         BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at         TIMESTAMP WITH TIME ZONE  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, sync_id)
);

-- 增量 Pull 的变更日志：change_id 单调递增，客户端按游标拉取。
CREATE TABLE sync_changes (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    entity_type        VARCHAR(20)  NOT NULL,
    sync_id            VARCHAR(36)  NOT NULL,
    version            BIGINT       NOT NULL,
    operation          VARCHAR(10)  NOT NULL,
    server_received_at TIMESTAMP WITH TIME ZONE  NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_sync_changes_user ON sync_changes (user_id, id);

CREATE TABLE conflict_logs (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    entity_type            VARCHAR(20)  NOT NULL,
    sync_id                VARCHAR(36)  NOT NULL,
    client_device_id       VARCHAR(64)  NOT NULL DEFAULT '',
    base_version           BIGINT       NOT NULL,
    server_version         BIGINT       NOT NULL,
    client_payload_digest  VARCHAR(64)  NOT NULL,
    server_payload_digest  VARCHAR(64)  NOT NULL,
    winner                 VARCHAR(10)  NOT NULL,
    created_at             TIMESTAMP WITH TIME ZONE  NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_conflict_logs_user ON conflict_logs (user_id, created_at);
