-- V3.2（多账本体系 + 家庭共享基础 + 权限安全）：
-- 1) Ledger 成为业务根节点：新建 ledgers / ledger_members / ledger_invitations，
--    五张业务表增加 ledger_id 并回填默认账本，服务端查询一律按账本隔离。
-- 2) 用户状态：users.status（ACTIVE/DISABLED），被禁用用户不能登录/刷新/同步。
-- 3) 游标升级：sync_changes 增加 ledger_id，拉取从「按用户」收紧为「按账本」。
-- 4) budgets 唯一键从 (user_id, 年, 月, 分类) 改为 (ledger_id, 年, 月, 分类)；
--    旧约束为匿名表级约束，无法跨 H2/PG 按名删除，故整表重建。

ALTER TABLE users ADD COLUMN status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE';

CREATE TABLE ledgers (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    sync_id             VARCHAR(36)  NOT NULL UNIQUE,
    name                VARCHAR(64)  NOT NULL,
    description         VARCHAR(255) NOT NULL DEFAULT '',
    currency            VARCHAR(8)   NOT NULL DEFAULT 'CNY',
    is_default          BOOLEAN      NOT NULL DEFAULT FALSE,
    is_archived         BOOLEAN      NOT NULL DEFAULT FALSE,
    version             BIGINT       NOT NULL DEFAULT 0,
    server_received_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted          BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at          BIGINT,
    created_at          TIMESTAMP WITH TIME ZONE  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          BIGINT       NOT NULL DEFAULT 0
);
CREATE INDEX idx_ledgers_owner ON ledgers (user_id);

CREATE TABLE ledger_members (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ledger_id    BIGINT      NOT NULL REFERENCES ledgers (id) ON DELETE CASCADE,
    user_id      BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role         VARCHAR(16) NOT NULL,
    status       VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    invited_by   BIGINT,
    invited_at   TIMESTAMP WITH TIME ZONE,
    accepted_at  TIMESTAMP WITH TIME ZONE,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (ledger_id, user_id)
);
CREATE INDEX idx_ledger_members_user ON ledger_members (user_id);

CREATE TABLE ledger_invitations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invitation_id   VARCHAR(36)  NOT NULL UNIQUE,
    ledger_id       BIGINT       NOT NULL REFERENCES ledgers (id) ON DELETE CASCADE,
    inviter_user_id BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    invitee_email   VARCHAR(255) NOT NULL,
    role            VARCHAR(16)  NOT NULL DEFAULT 'MEMBER',
    status          VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    accepted_at     TIMESTAMP WITH TIME ZONE,
    accepted_by     BIGINT
);
CREATE INDEX idx_invitation_email ON ledger_invitations (invitee_email, status);
CREATE INDEX idx_invitation_ledger ON ledger_invitations (ledger_id);

-- ===== 五张业务表增加 ledger_id 并回填默认账本 =====

ALTER TABLE categories ADD COLUMN ledger_id BIGINT;
ALTER TABLE accounts ADD COLUMN ledger_id BIGINT;
ALTER TABLE transactions ADD COLUMN ledger_id BIGINT;
ALTER TABLE budgets ADD COLUMN ledger_id BIGINT;
ALTER TABLE recurring_transactions ADD COLUMN ledger_id BIGINT;
ALTER TABLE sync_changes ADD COLUMN ledger_id BIGINT;
ALTER TABLE conflict_logs ADD COLUMN ledger_id BIGINT;

-- 每个已有用户生成「我的账本」（确定性 sync_id，跨 H2/PG 可移植）并授予 OWNER 成员资格。
INSERT INTO ledgers (user_id, sync_id, name, currency, is_default, version, created_at)
SELECT u.id, 'ledger-' || CAST(u.id AS VARCHAR(20)) || '-default',
       '我的账本', 'CNY', TRUE, 1, CURRENT_TIMESTAMP
FROM users u
WHERE NOT EXISTS (SELECT 1 FROM ledgers l WHERE l.user_id = u.id);

INSERT INTO ledger_members (ledger_id, user_id, role, status, accepted_at, created_at, updated_at)
SELECT l.id, l.user_id, 'OWNER', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM ledgers l
WHERE NOT EXISTS (
    SELECT 1 FROM ledger_members m WHERE m.ledger_id = l.id AND m.user_id = l.user_id);

UPDATE categories c SET ledger_id =
    (SELECT l.id FROM ledgers l WHERE l.user_id = c.user_id AND l.is_default = TRUE);
UPDATE accounts a SET ledger_id =
    (SELECT l.id FROM ledgers l WHERE l.user_id = a.user_id AND l.is_default = TRUE);
UPDATE transactions t SET ledger_id =
    (SELECT l.id FROM ledgers l WHERE l.user_id = t.user_id AND l.is_default = TRUE);
UPDATE budgets b SET ledger_id =
    (SELECT l.id FROM ledgers l WHERE l.user_id = b.user_id AND l.is_default = TRUE);
UPDATE recurring_transactions r SET ledger_id =
    (SELECT l.id FROM ledgers l WHERE l.user_id = r.user_id AND l.is_default = TRUE);
UPDATE sync_changes sc SET ledger_id =
    (SELECT l.id FROM ledgers l WHERE l.user_id = sc.user_id AND l.is_default = TRUE);
UPDATE conflict_logs cl SET ledger_id =
    (SELECT l.id FROM ledgers l WHERE l.user_id = cl.user_id AND l.is_default = TRUE);

ALTER TABLE categories ALTER COLUMN ledger_id SET NOT NULL;
ALTER TABLE accounts ALTER COLUMN ledger_id SET NOT NULL;
ALTER TABLE transactions ALTER COLUMN ledger_id SET NOT NULL;
ALTER TABLE budgets ALTER COLUMN ledger_id SET NOT NULL;
ALTER TABLE recurring_transactions ALTER COLUMN ledger_id SET NOT NULL;
ALTER TABLE sync_changes ALTER COLUMN ledger_id SET NOT NULL;

CREATE INDEX idx_categories_ledger ON categories (ledger_id);
CREATE INDEX idx_accounts_ledger ON accounts (ledger_id);
CREATE INDEX idx_transactions_ledger ON transactions (ledger_id);
CREATE INDEX idx_recurring_ledger ON recurring_transactions (ledger_id);
CREATE INDEX idx_sync_changes_ledger ON sync_changes (ledger_id, id);

-- ===== budgets 整表重建：唯一键从 user_id 收紧为 ledger_id =====

CREATE TABLE budgets_new (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    ledger_id           BIGINT      NOT NULL REFERENCES ledgers (id) ON DELETE CASCADE,
    sync_id             VARCHAR(36) NOT NULL,
    budget_year         INT         NOT NULL,
    budget_month        INT         NOT NULL,
    category_sync_id    VARCHAR(36) NOT NULL DEFAULT '',
    amount              BIGINT      NOT NULL DEFAULT 0,
    version             BIGINT      NOT NULL DEFAULT 0,
    server_received_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          BIGINT      NOT NULL DEFAULT 0,
    is_deleted          BOOLEAN     NOT NULL DEFAULT FALSE,
    deleted_at          BIGINT,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, sync_id),
    UNIQUE (ledger_id, budget_year, budget_month, category_sync_id)
);

INSERT INTO budgets_new (id, user_id, ledger_id, sync_id, budget_year, budget_month,
                         category_sync_id, amount, version, server_received_at,
                         updated_at, is_deleted, deleted_at, created_at)
SELECT id, user_id, ledger_id, sync_id, budget_year, budget_month, category_sync_id,
       amount, version, server_received_at, updated_at, is_deleted, deleted_at, created_at
FROM budgets;

DROP TABLE budgets;
ALTER TABLE budgets_new RENAME TO budgets;
CREATE INDEX idx_budgets_ledger ON budgets (ledger_id);
