-- V4.0（编辑账单退款）：退款成为第 7 个同步实体，服务端新增 refunds 表。
--
-- 口径与客户端一致：原账单金额永不改写，退款只以独立流水存在；
-- 「已退款 / 待到账」两个累计额是账单表上的缓存列，由客户端从本表重算，
-- 服务端不解释业务口径（与 transactions 一样只搬运事实）。
-- 参照完整性走服务层校验（transaction_sync_id 必须同账本存在），不建跨表外键，
-- 与 categories / accounts 的引用校验同构，避免 H2 与 PG 的删除顺序差异。

CREATE TABLE refunds (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    ledger_id           BIGINT      NOT NULL REFERENCES ledgers (id) ON DELETE CASCADE,
    sync_id             VARCHAR(36) NOT NULL,
    transaction_sync_id VARCHAR(36) NOT NULL,
    amount              BIGINT      NOT NULL,
    state               VARCHAR(16) NOT NULL,
    reason              VARCHAR(255) NOT NULL DEFAULT '',
    requested_at        BIGINT      NOT NULL,
    received_at         BIGINT,
    version             BIGINT       NOT NULL DEFAULT 0,
    server_received_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          BIGINT       NOT NULL DEFAULT 0,
    is_deleted          BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at          BIGINT,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, sync_id)
);
CREATE INDEX idx_refunds_ledger ON refunds (ledger_id);
CREATE INDEX idx_refunds_tx_ref ON refunds (ledger_id, transaction_sync_id);
